version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build || echo "No build step defined"
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
